### ISSUE TITLE
行为树黑板中保存的是map集合或者切片的时候，在黑板中Set或Get时出现错误

### ISSUE THREAD

**Issue by liguoguo520** [magicsea/behavior3go#14]
# 摘要

在行为树黑板中Set一个map，然后后面程序去修改map中的值，但是不往黑板中设置，然后接着在行为树中去Get黑板中的值，此时获取的`map`是程序修改之后的值。
## 复现步骤

1. 创建一个`map`集合
```go
mp:=make(map[int]int)
```
2. 给`map`集合赋值
```go
mp[0]=1
mp[1]=2
mp[2]=3
```
3. 然后设置到黑板中

```go
tick.Blackboard.Set(key.NowLockAddrs, mp, "", "")
```

4. 然后在```map```集合中添加或者删除修改值。

```go
mp[3]=4
```
5. 此时再去从黑板中获取该值
```go
getValue := tick.Blackboard.Get(key.NowLockAddrs, event.BlackboardScopeScu, "")
mp := getValue.(map[int]int)
fmt.Println(mp)
```
6. 然后从黑板中获取的值为：
```go
[0:1,1:2,2:3,3:4]
```
## 当前代码的错误行为
修改完`map`之后，没有将修改之后的值`Set`到黑板中，但是在`Get`黑板中该键对应的值的时候获取到修改后的`map`。

## 期望的正确行为
对map集合和切片这种数据设置到黑板中之后，如果在从黑板中Get的数据之前，对该map进行增删改的操作，在从黑板中Get的值仍是在黑板中Set的值，而不是修改map中的值之后不在黑板中Set也能获取到map修改后的值。

**Comment by magicsea** [comment]
这个是语法问题，map是引用类型。如果要不影响可以使用值类型

**Comment by liguoguo520** [comment]
如果我有个需求是需要使用引用类型的比如map或者切片存放在黑板中这样是不是就不支持了，请问有什么好的解决办法吗？

**Comment by liguoguo520** [comment]
对于引用类型即使不Set也能Get到修改后的值
