### ISSUE TITLE
关于lastOpenNodes的疑问

### ISSUE THREAD

**Issue by LouisSong** [magicsea/behavior3go#17]
![image](https://github.com/user-attachments/assets/b931ecd8-f43f-4680-8203-c0a683bba3cc)
请教一下，在关闭上一次的node时，图中代码从i索引处就出现不一致了，为什么start会比i值大1，i处的node不就漏掉close了吗？

**Comment by magicsea** [comment]
已修复，这个BUG会导致调用链的第一个记忆节点执行不到close，导致下次进入无法执行该节点OnOpen。
测试示例：https://github.com/magicsea/behavior3go/tree/master/examples/testwork
![image](https://github.com/user-attachments/assets/302b8244-8700-4455-b111-9aafad52e825)
