### ISSUE TITLE
一直显示Starting Application ... Have Fun

### ISSUE THREAD

**Issue by xuyang3232** [magicsea/behavior3go#4]
之前运行过这个桌面版编辑器，没问题。后来不知道怎么操作，打开后一直显示”Starting Application ... Have Fun”卡住不动。直接打开网页版也是如此，想请教是什么原因？

**Comment by xuyang3232** [comment]
找到原因了，behavioreditor运行后会在C:\Users\用户\AppData\Roaming\下创建一个b3editor文件夹，保存之前工程文件的位置信息等，如果想初始化可以把这个文件夹删除。

**Comment by magicsea** [comment]
编辑器BUG，会导致打开的时候预载上次打开的工程出错。web可以清空缓存，桌面版只能自己改源码不预载。我的编辑器分支去掉了预载，就没问题了https://github.com/magicsea/behavior3editor
