### ISSUE TITLE
如何返回值是running，但是下一帧出现了更高的条件，但是running还没有结束

### ISSUE THREAD

**Issue by mx5566** [magicsea/behavior3go#9]
选择了不是每次都从root开始执行行为树，每次都从running的节点开始出现下面的问题？

如何返回值是running，但是下一帧出现了更高的条件，但是running还没有结束，如何去打断这个running，让更高有优先级的去执行呢？

**Comment by magicsea** [comment]
如果进入running确实会一直进入直到running结束，设计如此。如果要running是可打断的，需要父节点加入一个selector节点，再加入一个condition来打断，如下图结构
                    ／break_condition
selector*－runningNode
